# Generated by Django 5.1.7 on 2025-04-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_document_document_type_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('certificat', 'Certificat'), ('diplome', 'Diplôme'), ('cv', 'CV'), ('lettre_motivation', 'Lettre de motivation'), ('stage', 'Stage'), ('accreditation', 'Accréditation professionnelle'), ('autre', 'Autre')], max_length=20),
        ),
    ]
