# Generated by Django 4.2 on 2025-04-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bloc_Per', '0002_alter_utilisateur_cne_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('Catégorie', models.CharField(max_length=255)),
                ('Création_date', models.DateField()),
                ('Description', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bloc_Per.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_article/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bloc_Per.article')),
            ],
        ),
    ]
