# Generated by Django 4.2 on 2025-04-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloc_Per', '0003_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(),
        ),
    ]
