# Generated by Django 4.2 on 2025-04-10 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bloc_Per', '0004_alter_utilisateur_date_naissance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_login',
        ),
    ]
