# Generated by Django 4.2 on 2025-04-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloc_Per', '0005_remove_utilisateur_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='article',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
