# Generated by Django 4.2 on 2025-04-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloc_Per', '0006_article_last_login_article_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='article',
            name='password',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
