# Generated by Django 4.2 on 2025-04-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloc_Per', '0007_remove_article_last_login_remove_article_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
