# Generated by Django 5.1.7 on 2025-04-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('cv', 'CV'), ('diploma', 'Diplôme'), ('certificate', 'Certificat'), ('grade', 'Relevé de notes'), ('other', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
